name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'plugins/**'
      - 'public/**'
      - 'index/**'
      - 'package.json'
      - 'gulpfile.js'
      - 'eslint.config.mjs'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'plugins/**'
      - 'public/**'
      - 'index/**'
      - 'package.json'
      - 'gulpfile.js'
      - 'eslint.config.mjs'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build (github)
      run: npm run build:web

    - name: Build (github)
      run: npm run build:github

    - name: Build (webos)
      run: npm run build:webos

    - name: Build (tizen)
      run: npm run build:tizen

    - name: Build (plugins)
      run: npm run build:plugins

    - name: Build (doc)
      run: npm run build:doc

    - name: Run tests
      run: npm run test
